# The configuration format is quite straight forward. It is organised in sections and key/value pairs.
# The order of the sections or key/values pairs inside the sections does not matter nor does casing.
# Boolean values can be set using true, false, 1 or 0
# Floating point values must use . (point) as decimal separator
[Gateway]
type=		# repeater, hotspot, dongle. Defaults to repeater
callsign=
address=0.0.0.0	        # this is the computer interface for the outgoing connection. Usually leave it blank and it will use whatever is avaiable.
icomAddress=172.16.0.20 
icomPort=20000          
hbAddress=             #address to use for connecting to the homebrew repeaters (MMDVMHost, DStarRepeater), defaults to 127.0.0.1
hbPort=20010
latitude=0.0
longitude=0.0
description1=
description2=
url=
language=              # valid values: english_uk, deutsch, dansk, francais, italiano, polski, english_us, espanol, svenska, nederlands_nl, nederlands_be, norsk, portugues

#up to 4 ircddb networks can be specified
[IRCDDB 1]
enabled=1
hostname=ircv4.openquad.net
username=              # The ircDDB username defaults to the value defined for gateway callsign.
password=

[IRCDDB 2]
enabled=0
hostname=
username=              # The ircDDB username defaults to the value defined for gateway callsign.
password= 

[IRCDDB 3]
enabled=0
hostname=
username=CHNGME         # The ircDDB username defaults to the value defined for gateway callsign.
password=

[IRCDDB 4]
enabled=0
hostname=
username=CHNGME         # The ircDDB username defaults to the value defined for gateway callsign.
password=

# up to 4 repeaters can be added
[Repeater 1]
enabled=1
band=B                  # Each module has to have a band letter
callsign=              # Has to be less than 8 characters, if empty gateway call will be used
address=		        # address where the repeater can be found, if left empty defaults to 127.0.0.1
port=20011
type=hb                 # valid values: hb or icom
reflector=
reflectorAtStartup=    # if reflector is set, this defaults to true
reflectorReconnect=30   # valid values: never, fixed, 5, 10, 15, 20, 25, 30, 60, 90, 120, 180
frequency=434.0
offset=-1.6
rangeKm=20
latitude=0.0
longitude=0.0
agl=
description1=
description2=
url=
band1=
band2=
band3=

[Repeater 2]
enabled=0
band=			# Each module has to have a band letter
callsign=		# Has to be less than 8 characters, if empty gateway call will be used
address=		# address where the repeater can be found, if left empty defaults to 127.0.0.1
port=20012
type=hb			# hb or icom
reflector=
reflectorAtStartup=1
reflectorReconnect=30 # never, fixed, 5, 10, 15, 20, 25, 30, 60, 90, 120, 180
frequency=434.0
offset=-1.6
rangeKm=20
latitude=0.0
longitude=0.0
agl=
description1=
description2=
url=
band1=
band2=
band3=

[Repeater 3]
enabled=0
band=			# Each module has to have a band letter
callsign=		# Has to be less than 8 characters, if empty gateway call will be used
address=		# address where the repeater can be found, if left empty defaults to 127.0.0.1
port=20013
type=hb			# hb or icom
reflector=
reflectorAtStartup=1
reflectorReconnect=30 # never, fixed, 5, 10, 15, 20, 25, 30, 60, 90, 120, 180
frequency=434.0
offset=-1.6
rangeKm=20
latitude=0.0
longitude=0.0
agl=
description1=
description2=
url=
band1=
band2=
band3=

[Repeater 4]
enabled=0
band=			# Each module has to have a band letter
callsign=		# Has to be less than 8 characters, if empty gateway call will be used
address=		# address where the repeater can be found, if left empty defaults to 127.0.0.1
port=20014
type=hb			# hb or icom
reflector=
reflectorAtStartup=1
reflectorReconnect=30 # never, fixed, 5, 10, 15, 20, 25, 30, 60, 90, 120, 180
frequency=434.0
offset=-1.6
rangeKm=20
latitude=0.0
longitude=0.0
agl=
description1=
description2=
url=
band1=
band2=
band3=

[APRS]
enabled=1
positionSource=           # Sets how the position is determined fixed or gpsd. this is ignored if DStargateway was built without GPSD support

[GPSD]
address=                  # GPSD address, defaults to 127.0.0.1
port=                     # GPSD port, defaults to 2947

[Log]
mqttLevel=      # defaults to info, valid values are trace, debug, info, warning, error, fatal, none
displayLevel=   # defaults to info, valid values are trace, debug, info, warning, error, fatal, none
logIRCDDBTraffic=#Set to true to output ircddb traffic to the log, defaults to false

[MQTT]
address=	# address of the MQTT broker, defaults to 127.0.0.1
port=		# port of the MQTT broker, defaults to 1883
keepalive=	# the MQTT keepalive timer, defaults to 60
authenticate=	# whether to use MQTT authentication, defaults to false
username=	# the username for MQTT authentication if enabled
password=	# the password for MQTT authentication if enabled
name=		# the name of this MQTT client, default is "dstar-gateway"

[Paths]
data=/usr/local/share/dstargateway.d/ # Path where the data (audio files etc) can be found

[Hosts Files]
downloadedHostsFiles=/usr/local/share/dstargateway.d/ # Path where the downloaded host files are stored, make sure user dstar has write access
downloadTimer= # Redownload host files every X hours, must be greater than 24 hours. Defaults to 72 hours
customHostsfiles=/usr/local/share/dstargateway.d/hostfiles.d/  # Place your custom host files in this directory, this dir must be different from datadir. 
                                                              # Any hosts found here will override same host in downloaded files
                                                
[Dextra]
enabled=1 # There is no reason to disable this
maxDongles=5

[D-Plus]
enabled=1 # There is no reason to disable this
maxDongles=5
login= # defaults to gateway callsign

[DCS]
enabled=1 # There is no reason to disable this

[XLX]
enabled=1 

[D-Rats]
enabled=0 # Defaults to false. The program need to be compiled with DRats support for DRats to be actually enabled

[Remote Commands]
enabled=0
port=4242
password=CHANGE_ME # If password is left blank, remote will be disabled regardless of the enabled field

# Should only be used with respect to your local regulation! Many countries prohibit setting up private repeaters !
[Access Control]
whiteList= # Only affects network
blackList= # Only affects network
restrictList= # Only affects RF, call signs present in this list are now allowed to change reflector or unlink the repeater

# The Provided install routines install the program as a systemd unit. SystemD does not recommand "old-school" forking daemons nor does systemd
# require a pid file. Moreover systemd handles the user under which the program is started. This is provided as convenience for people who might
# run the program using sysv or any other old school init system.
[Daemon]
daemon=0
pidfile=/var/run/dstargateway/dstargateway.pid # pid file is in our case useless when running as a daemon  using systemd as systemd takes care of the service not being started twice
user=dstar # user account the daemon will run under, ideally a user with low privileges. Switching to this user will only happen when the program is started as root

